(require 'tex-mode)

(defun my/more-prettified-symbols ()
  (mapc (lambda (pair) (cl-pushnew pair tex--prettify-symbols-alist))
        '(("\\Z" . 8484)
          ("\\Q" . 8474)
          ("\\N" . 8469)
          ("\\R" . 8477)
          ("\\eps" . 949)
          ("\\ONE" . #x1D7D9)
          ("\\ind" . #x1D7D9)
          ("\\P" . #x1D5AF)
          ("\\E" . #x1D53C)
          ("\\T" . #x1D4E3)
          ("\\l" . #x1D4C1)
          ("\\defeq" . #x2254)
          ("\\eqdef" . #x2255)
          )))

(my/more-prettified-symbols)
